### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-proc-provider#2]
```
Error: An error occured while performing a request: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data core.js:394:14 
```

Code being used:
```
            core.make('osjs/proc').spawn({
              cmd: 'sudo',
              env: {
                DISK: '/dev/' + state.disk.disk.name,
                EFI: state.disk.efi.toString(),
                STATISTICS: state.personalization.statistics.toString(),
                NEW_HOSTNAME: state.personalization.hostname,
                USERS: JSON.stringify(state.usersList.rows),
                LANGUAGE: state.lang,
                TIMEZONE: state.timezone.city === null ? state.timezone.region : state.timezone.region + '/' + state.timezone.city.split(' ').join('_')
              }
            }, [
              '-S',
              '-E',
              '/usr/bin/bash',
              '-e',
              '/usr/lib/node_modules/@bluelightos/installer-application/install.sh'
            ]).then(p => {
              p.on('data', data => {
                try {
                  let msg = JSON.parse(data.toString());
                  core.make('osjs/dialog', 'alert', {
                    message: msg.message,
                    title: msg.name
                  }, (btn, value) => {});
                  p.kill();
                } catch (ex) {
                  actions.updateLog(data.toString());
                }
              });
              p.on('error', err => {
                core.make('osjs/dialog', 'alert', {
                  message: err.message,
                  title: err.name
                }, (btn, value) => {});
                p.kill();
              });
              p.on('exit', () => {
                core.make('osjs/dialog', 'alert', {
                  message: _('INSTALL_COMPLETE')
                }, (btn, value) => {});
              });
              p.write('bluelight\n');
});
```

**Comment by andersevenrud** [comment]
Are you running latest version of OS.js libraries ? Also, is is this error from the server or the client ?
And is there a stack trace ?

A few notes:

1. Arguments are sent as arguments, not array: `.spawn(cmd, arg1, arg2, arg3)`.
2. You're killing the application when you get data
3. You can use your raw data and stringify it and use it as an argument for your process instead of using *environmental* variables

**Comment by RossComputerGuy** [comment]
Error is from client. Running latest libraries.

**Comment by andersevenrud** [comment]
What was the response from the server ? My two cents is that that's where it went wrong judging by the "at line 1 column 1".

Without any stack traces or more details, I can't really do anything, sadly.

**Comment by RossComputerGuy** [comment]
There was no stack trace so I can’t provide that.

**Comment by RossComputerGuy** [comment]
Here's a screenshot of the error:
![virtualbox](https://user-images.githubusercontent.com/19699320/52166793-cf9c0700-26c6-11e9-80de-17e03fa8cae7.png)
And I kill the process so it doesn't continue on error. I also updated the code to be this:
```js
            core.make('osjs/proc').spawn({
              cmd: 'sudo',
              env: {
                DISK: '/dev/' + state.disk.disk.name,
                EFI: state.disk.efi.toString(),
                STATISTICS: state.personalization.statistics.toString(),
                NEW_HOSTNAME: state.personalization.hostname,
                USERS: JSON.stringify(state.usersList.rows),
                LANGUAGE: state.lang,
                TIMEZONE: state.timezone.city === null ? state.timezone.region : state.timezone.region + '/' + state.timezone.city.split(' ').join('_')
              }
            }, '-S', '-E', '/usr/bin/bash', '-e', '/usr/lib/node_modules/@bluelightos/installer-application/install.sh').then(p => {
              p.on('data', data => {
                try {
                  let msg = JSON.parse(data.toString());
                  core.make('osjs/dialog', 'alert', {
                    message: msg.message,
                    title: msg.name
                  }, (btn, value) => {});
                  p.kill();
                } catch (ex) {
                  actions.updateLog(data.toString());
                }
              });
              p.on('error', err => {
                core.make('osjs/dialog', 'alert', {
                  message: err.message,
                  title: err.name
                }, (btn, value) => {});
                p.kill();
              });
              p.on('exit', () => {
                core.make('osjs/dialog', 'alert', {
                  message: _('INSTALL_COMPLETE')
                }, (btn, value) => {});
              });
              p.write('bluelight\n');
            });
```

**Comment by andersevenrud** [comment]
This doesn't really tell me anything, sorry.

It would be best if you inspect your HTTP calls and/or check logs etc.

> And I kill the process so it doesn't continue on error. I also updated the code to be this:

But, you're killing it in the `data` event which doesn't even trigger on  `.spawn()` -- that's for `.pty()`.

**Comment by RossComputerGuy** [comment]
So I guess I should use `.pty()` instead of `.spawn()`.

**Comment by andersevenrud** [comment]
That wasn't really my point. You'll probably get the same error.

**Comment by RossComputerGuy** [comment]
Will not killing the process fix it?

**Comment by andersevenrud** [comment]
Since I don't know *when* this error occurs I really don't know. But I assume not since I suspect this occurs before it even gets spawned. I need more info.

**Comment by RossComputerGuy** [comment]
It happens on line 394 of `core.js`.

**Comment by RossComputerGuy** [comment]
![virtualbox](https://user-images.githubusercontent.com/19699320/52167561-acc32000-26d1-11e9-966b-636045705c84.png)
I got some more details.

**Comment by andersevenrud** [comment]
Doesn't seem like the sourcemap files are used, and therefore the error messages doesn't reflect the actual code -- so I can't get anything out of it.

It's much easier if you just use devtools to extract any stack traces and networking logs.

**Comment by RossComputerGuy** [comment]
So I figured out it's failing on line 394 of `@osjs/client/src/core.js`. Which on that line is:
```js
throw new Error(_('ERR_REQUEST_NOT_OK', error));
```

And a status code of 403.

**Comment by andersevenrud** [comment]
> And a status code of 403.

Now, this is useful!

403 means that the user you're logged in as does not have the correct permissions (groups).

**Comment by RossComputerGuy** [comment]
So I think the details of the error should be improved so the user/developer will know it's a permissions issue.

**Comment by andersevenrud** [comment]
That's actually how it is supposed to work, however in this instance the issue was the parsing of the error message.

So I'll get that fixed.

**Comment by andersevenrud** [comment]
This was fixed in https://github.com/os-js/osjs-client/commit/b7a2a45f472e9aaea237a86cfa333c1169fb6620

Which has also been published to npm.
