### ISSUE TITLE
Add support for "attachShell" for attaching a shell to arbitrary GUI

### ISSUE THREAD

**Issue by andersevenrud** [os-js/osjs-proc-provider#3]
Right now the only way to get a properly rendered shell (i.e. *not* a textbox) is to use the `.createWindow()` method.

It would be nice to have `attachShell(container: HTMLElement)` as well so you can attach to already existing window UIs, etc.

**Comment by andersevenrud** [comment]
Maybe a GUI component that wraps up the proc API as well.

**Comment by RossComputerGuy** [comment]
This would be very useful.

**Comment by andersevenrud** [comment]
I think I've come up with a nice solution for this. Just gotta add support for "local focus" (i.e. not the entire window decides the focus as on Xterm application), and this is good to go.

The idea is just to make a basic component that the xterm attaches to via `p.attachXterm(xterm)` when a process is created.

```javascript
// Create a hyperapp component
const XtermElement = props => h('div', {
  class: 'osjs-gui osjs-gui-xterm', // Included with the proc-provider stylesheet
  oncreate: el => props.xterm.open(el)
});

// Example implementation
    .render(($content, win) => {
      const pp = core.make('osjs/proc');
      const xterm = pp.xterm(win);

      app({

      }, {
        runPty: () => {
          pp.pty('ls', '-l')
            .then(p => p.attachXterm(xterm))
            .catch(error => console.error(error));
        }
      }, (state, actions) => {
        return h(Box, {
          grow: 1,
          shrink: 1
        }, [
          h(Toolbar, {}, [
            h(Button, {onclick: () => actions.runPty()}, 'pty()')
          ]),
          h(XtermElement, {
            xterm
          })
        ]);
      }, $content);
    });
```

**Comment by andersevenrud** [comment]
@hanswurmwurst2 I have now added support for this in the latest update.

The `README.md` file has been updated with an example.
