### ISSUE TITLE
Cannot run commands even though user is in the group

### ISSUE THREAD

**Issue by RossComputerGuy** [os-js/osjs-proc-provider#4]

**Comment by andersevenrud** [comment]
There's no information here.

I need at least an example *and* the respons(es) you get.

**Comment by RossComputerGuy** [comment]
Code:
```
core.make('osjs/proc').pty({
            cmd: 'sudo',
            env: {
              DISK: '/dev/' + state.disk.disk.name,
              EFI: state.disk.efi.toString(),
              STATISTICS: state.personalization.statistics.toString(),
              NEW_HOSTNAME: state.personalization.hostname,
              USERS: JSON.stringify(state.usersList.rows),
              LANGUAGE: state.lang,
              TIMEZONE: state.timezone.city === null ? state.timezone.region : state.timezone.region + '/' + state.timezone.city.split(' ').join('_')
            }
}, '-S', '-E', '/usr/bin/bash', '-e', '/usr/lib/node_modules/@bluelightos/installer-application/install.sh').then(p => {
            p.on('data', data => {
              try {
                let msg = JSON.parse(data.toString());
                core.make('osjs/dialog', 'alert', {
                  message: msg.stack,
                  title: msg.name
                }, (btn, value) => {});
                p.kill();
              } catch (ex) {
                actions.updateLog(data.toString());
              }
            });
            p.on('error', err => {
              core.make('osjs/dialog', 'alert', {
                message: err.stack,
                title: err.name
              }, (btn, value) => {});
              p.kill();
            });
            p.on('exit', () => {
              core.make('osjs/dialog', 'alert', {
                message: _('INSTALL_COMPLETE')
              }, (btn, value) => {});
            });
            p.write('bluelight\n');
});
```

Response: Permission error

What is going on:
User is in the group and `osjs/proc-provider` is configured to use that group. The code results in a permission error.

**Comment by andersevenrud** [comment]
Can you put your server code here as well ?

And paste the actual full response.

**Comment by RossComputerGuy** [comment]
Part of the server config:
```
  auth: {
    defaultGroups: ['bluelight']
  },
```
Part of the server index.js file:
```
osjs.register(ProcServiceProvider, {
  args: {
    groups: ['bluelight']
  }
});
```
Full response is not available as I don't have time but the network tab is saying 400 for the request, I am just trying to recall what I saw.

**Comment by andersevenrud** [comment]
A 403 usually means that you cannot access the API.

A 400 error usually comes from the API itself, so I need to see the full error because I suspect it's from the system, not express.

**Comment by RossComputerGuy** [comment]
The only error I saw and can remember on screen from a dialog was `Permission Error`.

**Comment by andersevenrud** [comment]
Paste or screenshot the full error message (from network log) here when you have the time and I'll assist further.

**Comment by RossComputerGuy** [comment]
![virtualbox](https://user-images.githubusercontent.com/19699320/52585357-5f3d6600-2de9-11e9-9fb9-b2140080ab7b.png)

**Comment by andersevenrud** [comment]
Are you using pam auth here ?

**Comment by RossComputerGuy** [comment]
Yes

**Comment by andersevenrud** [comment]
The latest pam auth reads the *real* user groups, so your defaultGroups won't apply unless your user has zero system groups.

So your system user most likely will need the `bluelight` group, or that you change your config.

**Comment by RossComputerGuy** [comment]
They do have that group.

**Comment by andersevenrud** [comment]
And you can confirm this in the network log with the login response ?

**Comment by RossComputerGuy** [comment]
Payload for the response of `login`:
```json
{"id":1000,"username":"bluelight","name":"bluelight","groups":["network","power","wheel","input","users"]}
```

**Comment by RossComputerGuy** [comment]
![virtualbox](https://user-images.githubusercontent.com/19699320/52586111-86953280-2deb-11e9-8468-cd8e70bb0379.png)
So `pam` forgot a group.

**Comment by RossComputerGuy** [comment]
Moving to https://github.com/os-js/osjs-pam-auth/issues/5 as this is a PAM issue
