### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by msjavan** [os-js/osjs-proc-provider#5]
I got error 403 on invoking any methods.

### **Client Side:**
**OSjs.make('osjs/proc').spawn('ls', '-l')** 

_Promise {<resolved>: t}
__proto__: Promise
[[PromiseStatus]]: "resolved"
[[PromiseValue]]: t
name: "41d6f22d-72a5-4a56-a0b8-000f646d570b"
events: {exit: Array(1), spawned: Array(1), destroy: Array(2)}
service: t {name: "ProcService", events: {…}, core: Core, processes: Array(5)}
cmd: "ls"
args: ["-l"]
destroyed: false
pingInterval: null
win: null
__proto__: e_

### **Some Server side logs:**
POST /proc/spawn 403 13 - 1.590 ms
POST /proc/pty 403 13 - 1.475 ms
POST /proc/exec 403 13 - 1.529 ms
...

**Comment by andersevenrud** [comment]
Can you check the actual response data in devtools ?

**Comment by msjavan** [comment]
This was response data:

Promise {: t}
proto: Promise
[[PromiseStatus]]: "resolved"
[[PromiseValue]]: t
name: "41d6f22d-72a5-4a56-a0b8-000f646d570b"
events: {exit: Array(1), spawned: Array(1), destroy: Array(2)}
service: t {name: "ProcService", events: {…}, core: Core, processes: Array(5)}
cmd: "ls"
args: ["-l"]
destroyed: false
pingInterval: null
win: null
proto: e

**Comment by msjavan** [comment]
Here is the screenshot:

![Screenshot from 2020-03-18 09-36-38](https://user-images.githubusercontent.com/5146431/76930589-15805280-68fc-11ea-8f48-a51544b87ca8.png)

**Comment by andersevenrud** [comment]
You have to look at the Network tab in devtools to see the response data.

**Comment by andersevenrud** [comment]
I think this is probably because you don't belong to the "admin" group.

You can disable or change this as you wish: https://github.com/os-js/osjs-proc-provider#configuration

**Comment by andersevenrud** [comment]
I'm closing this issue because I believe the previous comment should take care of your issue :)
